version: "3.9"
services:
  dev_container:
    container_name: "rust"
    hostname: "rust"
    build: .
    restart: always
    working_dir: "/workspace"
    tty: true
    # Bind the workspace dir of the host to that of the container
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace
